#!/bin/bash

# logs data to file every 2 seconds
while true; do
	cpu_usage=$(top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print 100 - $1"%"}')
	mem_usage=$(free -m | grep Mem | awk '{print $3/$2 * 100 "%"}')
	current_time=$(date)
	echo "CPU usage: $cpu_usage, Memory usage: $mem_usage $current_time" >> sys_log
	sleep 2
done	
